name: "Build"
on:
  workflow_dispatch:
  # push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - melodic
          - melodicPython3
          - noetic
          - foxy
          - galactic
        system:
          - x86_64-linux
          - aarch64-linux
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        extra_nix_config: |
          max-jobs = 1
          extra-platforms = aarch64-linux
    - uses: docker/setup-qemu-action@v1
    - uses: cachix/cachix-action@v9
      with:
        name: ros
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipPush: true
    - name: Cache Failed Builds
      id: cache-failed-builds
      uses: actions/cache@v2
      with:
        path: failed-builds
        key: failed-builds-${{ matrix.distro }}-${{ matrix.system }}-${{ github.sha }}
        #restore-keys: |
        #  failed-builds-${{ matrix.distro }}-${{ matrix.system }}-
    - uses: ./.github/actions/nix-ros-build-action
      with:
        root-attribute: '${{ matrix.distro }}'
        system: '${{ matrix.system }}'
